name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  deploy:
    runs-on: ubuntu-20.04

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Install dependencies
        run: npm ci --production

      - name: Build page
        run: npm run build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ github.token }}
          cname: rynali-goals.xyz
